### ISSUE TITLE
I cant see my pity count in Character Event Wish

### ISSUE THREAD

**Issue by meryem-dotcom** [forkpoweroutlet/genshin-pity-calculator#30]
It always says Error: Double-check that you copied and pasted correctly and let me know if you still think something's wrong. 
I didnt get a 5* yet, also on Asia server

(It works on permanent wish tho)

Select Wish Type:
Character Event Wish

You can check the wishes you made in the past six months. Wish records are updated about one hour after the wish is made. If there is no record yet, please check again later. The times displayed below are according to your current server time. Please note any difference between the time zone of your server and the time zone of where you are located. Server time zones: 天空岛 (UTC+8); 世界树 (UTC+8); TW, HK, MO (UTC+8); Asia (UTC+8); Europe (UTC+1); America (UTC-5)
Item Type Item Name Time Received
Weapon
Magic Guide
2021-08-09 01:11:28
Weapon
Raven Bow
2021-08-09 01:08:57
Weapon
Slingshot
2021-08-09 01:08:45
Weapon
Magic Guide
2021-08-09 01:08:34
Weapon
Sharpshooter's Oath
2021-08-09 01:08:23
Weapon
Ferrous Shadow
2021-08-09 01:08:07
 11

**Comment by geodude1000** [comment]
The calculator only works if you have gotten a 5* before! You currently have (at least) 60-66 pity. You can do the math yourself by doing the amount of pages (in this case 11) times 6, and then substracting how many you are missing to have another full page (for example, if on page 1 you have 4, substract 2). good luck!

**Comment by Jiooooooo** [comment]
Ignore my other reply, I gave some misinformation (I deleted it as soon as I could).

The calculator only works if you have gotten a 5* before. You currently have 66 pity. You can do the math yourself by doing the amount of pages (in this case 11), minus 1, times 6, plus the amount of things in your last page (in this case 6). Keep in mind this only has pulls from the last 6 months. If you have pity from older than that, you still have it, but it will not be picked up by the calculator. Good luck on your wishes!

**Comment by meryem-dotcom** [comment]
Well then i dont have to wait anymore :D

Select Wish Type:
Character Event Wish

You can check the wishes you made in the past six months. Wish records are updated about one hour after the wish is made. If there is no record yet, please check again later. The times displayed below are according to your current server time. Please note any difference between the time zone of your server and the time zone of where you are located. Server time zones: 天空岛 (UTC+8); 世界树 (UTC+8); TW, HK, MO (UTC+8); Asia (UTC+8); Europe (UTC+1); America (UTC-5)
Item Type Item Name Time Received
Weapon
Cool Steel
2021-09-13 01:17:54
Weapon
Favonius Greatsword (4-Star)
2021-09-12 21:35:27
Character
Jean (5-Star)
2021-09-12 06:28:28
Weapon
Thrilling Tales of Dragon Slayers
2021-09-12 06:28:18
Weapon
Cool Steel
2021-09-12 06:28:08
Character
Raiden Shogun (5-Star)
2021-09-12 06:22:21
 2

**Comment by Jiooooooo** [comment]
nice :)
